spring:
  application:
    name: halm-export
  datasource:
    url: jdbc:oracle:thin:@db.hzero.org:1521:DEV
    username: hzero
    password: hzero
    tomcat:
      # 并发情况下最大可从连接池中获取的连接数
      # 默认100，设置值视系统负载而定
      max-active: 200
      # 最大空闲连接数，
      # 默认值=maxActive，设置值视系统负载而定
      max-idle: 60
      # 最大等待时间(单位毫秒)，当没有可用连接时，连接池等待连接释放的最大时间，超过该时间限制会抛出异常。
      # 默认30秒，-1表示无限等待，可根据实际情况调整，避免因线程池不够用，而导致请求被无限制挂起
      max-wait: 30000
  redis:
    host: redis.hzero.org
    port: 6379
    database: 1
    pool:
      # 资源池中最大连接数
      # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整
      max-active: 50
      # 资源池运行最大空闲的连接数
      # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整，一般建议和max-active保持一致，避免资源伸缩带来的开销
      max-idle: 50
      # 当资源池连接用尽后，调用者的最大等待时间(单位为毫秒)
      # 默认 -1 表示永不超时，设置5秒
      max-wait: 5000
  resources:
    # 资源缓存时间，单位秒
    cache-period: 3600
    # 开启gzip压缩
    chain.gzipped: true
    # 启用缓存
    chain.cache: true

server:
  session:
    timeout: 3600
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接
    # 默认值为8，建议设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程
    # 默认等于 io-threads*8，它的值设置取决于系统的负载，可适当调大该值
    worker-threads: 128
    # 每块buffer的空间大小，越小空间被利用越充分
    # 不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024
    # 是否分配的直接内存(NIO直接分配的堆外内存)
    # 默认false
    direct-buffers: true
    # HTTP POST请求最大的大小
    # 默认0，无限制，可设置10M
    max-http-post-size: 10485760

feign:
  hystrix:
    enabled: true

hystrix:
  threadpool:
    default:
      # 执行命令线程池的核心线程数，也是命令执行的最大并发量
      # 默认10
      coreSize: 1000
      # 最大执行线程数
      maximumSize: 1000
  command:
    default:
      execution:
        isolation:
          thread:
            # HystrixCommand 执行的超时时间，超时后进入降级处理逻辑。一个接口，理论的最佳响应速度应该在200ms以内，或者慢点的接口就几百毫秒。
            # 默认 1000 毫秒，最高设置 2000足矣。如果超时，首先看能不能优化接口相关业务、SQL查询等，不要盲目加大超时时间，否则会导致线程堆积过多，hystrix 线程池卡死，最终服务不可用。
            timeoutInMilliseconds: 40000

ribbon:
  # 客户端读取超时时间，超时时间要小于Hystrix的超时时间，否则重试机制就无意义了
  ReadTimeout: 30000
  # 客户端连接超时时间
  ConnectTimeout: 3000
  # 访问实例失败(超时)，允许自动重试，设置重试次数，失败后会更换实例访问，请一定确保接口的幂等性，否则重试可能导致数据异常。
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true


logging:
  level:
    org.apache.ibatis: debug
    io.choerodon: debug
    org.hzero: debug

